config/routes.rb
Rails.application.routes.draw do
  get 'questions/show'
  get 'quizzs/index'
  get 'quizzs/show'
  get 'locations/index'
  get 'steps/index'

  # get 'aids/index'
  # get 'aids/show'
  # get 'emergencies/index'
  # get 'emergencies/show'

  devise_for :users
  root to: "pages#home"
  resources :pages , only: %i[index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :emergencies, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :aids, only: [:index, :show]
  resources :locations, only: [:index]

  resources :quizzs, only: %i[index show]
  resources :questions , only: %i[show]

end

app/models/aid.rb
class Aid < ApplicationRecord
  has_one_attached :photo
  has_many :steps

  after_create do
    puts name
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/emergency.rb
class Emergency < ApplicationRecord
  has_one_attached :photo
  belongs_to :user

  validates :name, presence: true

  validates :phone_number, presence: true
  validates :phone_number, format: { with: /\A(\+230)?((\d{3})|(\d{8})|(\d{7}))\z/ }

  validates :ispublic, inclusion: [true, false]

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quizz
end

app/models/quizz.rb
class Quizz < ApplicationRecord
  has_many :questions, dependent: :destroy
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :aid
  has_one_attached :photo

  after_create do
    puts position
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :emergencies, dependent: :destroy
end

app/controllers/aids_controller.rb
class AidsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    if params[:query].present?
      @aids = policy_scope(Aid.where("name ILIKE ?", "%#{params[:query]}%"))
    else
      @aids = policy_scope(Aid)
    end
  end

  def show
    @aid = Aid.find(params[:id])
    @steps = @aid.steps.order(:position)
    authorize @aid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  # app/controllers/application_controller.rb

  def default_url_options
    { host: ENV["sauce-mu.herokuapp.com"] || "localhost:3000" }
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/emergencies_controller.rb
class EmergenciesController < ApplicationController
  def index

    if params[:query].present?
      @emergencies = policy_scope(Emergency.where("name ILIKE ?", "%#{params[:query]}%"))
    else
      @emergencies = policy_scope(Emergency)
    end

  end

  def show
    @emergency = Emergency.find(params[:id])
    authorize @emergency
  end

  def new
    @emergency = Emergency.new
    authorize @emergency
  end

  def create
    @emergency = Emergency.new(emergency_params)
    @emergency.user = current_user
    authorize @emergency
    if @emergency.save
      redirect_to emergencies_path
    else
      render :new, status: :unprocessable_entity
    end

  end

  def edit
    @emergency = Emergency.find(params[:id])
    authorize @emergency
  end

  def update
    @emergency = Emergency.find(params[:id])
    authorize @emergency
    if @emergency.update(emergency_params)
      redirect_to emergencies_path, notice: "list was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @emergency = Emergency.find(params[:id])
    authorize @emergency
    @emergency.destroy
    redirect_to emergencies_path, status: :see_other
  end

  private
  def emergency_params
    params.require(:emergency).permit(:name, :phone_number)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    skip_policy_scope
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :show ]

  def home
  end

  def index
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
  end
end

app/controllers/quizzs_controller.rb
class QuizzsController < ApplicationController
  def index
    if params[:query].present?
      @quizzs = policy_scope(Quizz.where("name ILIKE ?", "%#{params[:query]}%"))
    else
      @quizzs = policy_scope(Quizz)
    end
  end

  def show
    @quizz = Quizz.find(params[:id])
    authorize @quizz
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def index
    @steps = Step.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/aids/index.html.erb
<div class="container vh-100">

  <section id="aid">
    <h2>My first-aid guide</h2>
    <%# search_bar %>
    <%= form_with url: aids_path, method: :get, class: "d-flex search_bar" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control search_icon",
          placeholder: "   Search"
        %>
        <button name="button" type="submit" class="btn btn-flat inner_icon">
          <i class="fas fa-search "></i>
        </button>
    <% end %>

  <%# OT_front %>
    <section class="cat__cards">
      <% @aids.each do |aid| %>
        <%= link_to aid_path(aid) do %>
          <div class="cat__card">
            <%= aid.name %>
            <%= cl_image_tag aid.photo.key, class:"aid-category-image", :crop => "fit" %>
          </div>
        <% end %>
      <% end %>
    </section>


  </section>
</div>

app/views/aids/show.html.erb
<div class="container vh-100 mb-5 pb-5">
  <section id="step">
    <h2><%= @aid.name%></h2>
      <section class="cat__card">
        <% @steps.each do |step| %>
          <%= cl_image_tag step.photo.key, id:"step__img", :crop => "fit"%>
          <h3>STEP: <%= step.position %></h3>
          <p><%= step.description %></p>
          <hr>
        <% end %>
      </section>
  </section>
</div>

app/views/emergencies/edit.html.erb
<div class="container vh-100">
  <section id="edit_em">
    <h2>Edit my contact</h2>
    <%= simple_form_for ([@emergency]) do |f| %>
      <%= f.input :name %>
      <%= f.input :phone_number %>
      <%= f.submit id: 'btn' %>
    <% end %>
  </section>
</div>

app/views/emergencies/index.html.erb
<div class="container vh-100">
  <section id="default__emergency">
    <h2>My emergency list</h2>

    <%= form_with url: emergencies_path, method: :get, class: "d-flex search_bar" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control search_icon",
        placeholder: "   Search"
      %>
      <button name="button" type="submit" class="btn btn-flat inner_icon">
        <i class="fas fa-search "></i>
      </button>
    <% end %>

    <div class="cat__cards">
      <% @emergencies.each do |emergency| %>
          <div class="<%= emergency.user == current_user ? "cat__card" : "cat__c" %> ">
            <h3><%= emergency.name %></h3>
            <p><%= emergency.phone_number %></p>
            <%= phone_to emergency.phone_number, "call", class:"#{ emergency.ispublic ? "btn-default" : "btn-new" }"%>
            <% if emergency.user == current_user %>
              <%# <%= sms_to emergency.phone_number, "Alert", class: "btn-new", body: "I need help" %>
              <%# <%= link_to "Edit",  edit_emergency_path(emergency), class: "btn-new"%>
              <%# <%= link_to "delete", emergency_path(emergency), data: { turbo_method: :delete , turbo_confirm: "Are you sure you want to remove this number"}, class: "btn-new" %>
              <br>
              <br>

              <%= sms_to emergency.phone_number, class: "icon_e" do %>
                <i class="fa-solid fa-message"></i>
              <% end %>
              <%= link_to edit_emergency_path(emergency), class: "icon_e" do %>
                <i class="fa-solid fa-pen-to-square"></i>
              <% end %>
              <%= link_to emergency_path(emergency), class: "icon_e", data: { turbo_method: :delete , turbo_confirm: "Are you sure you want to remove this number"} do %>
                <i class="fa-solid fa-trash"></i>
              <% end %>
            <% end %>
          </div>
      <% end %>
    </div>


  </section>

  <section id="create">
      <%= link_to new_emergency_path do %>
        <i class="fa-solid fa-circle-plus" id="plus"></i>
      <% end %>
  </section>
</div>

app/views/emergencies/new.html.erb
<div class="container vh-100">
  <section id="create_em">
    <h2>My new contact</h2>
    <%= simple_form_for ([@emergency]) do |f| %>
      <%= f.input :name %>
      <%= f.input :phone_number %>
      <%= f.submit id: 'btn' %>
    <% end %>
  </section>
</div>

app/views/emergencies/show.html.erb
<h1>Emergencies#show</h1>
<p>Find me in app/views/emergencies/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%# flavicons %>
    <%# <%= favicon_link_tag %>
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <%# PWA %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: false %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>

    <%= render "shared/nav_footer" %>
  </body>

</html>

app/views/locations/index.html.erb
<div class="container vh-100">
  <section id="location">
    <h2>My Location</h2>
    <div class="map-container" style="width: 100%; height: 600px;"
      data-controller="map"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </section>
</div>

<%# <pre id="info"></pre> %>

app/views/pages/home.html.erb
<div class="container vh-100">

  <section>
    <%= image_tag "Final_img.svg", class:"ImgSauce" %>
    <%# <%= image_tag "es2.png", class:"ImgSauce" %>
  </section>

  <section id="about">
    <h2>Your Life saver, in your pocket!</h2>
  </section>

  <section id="categories">
    <div class="container cat__cards">

      <%= link_to emergencies_path do %>
        <div class="cat__card">
          <i class="fa-solid fa-phone" id= "icon"></i>
          <h3>Emergencies</h3>
        </div>
      <% end %>

      <%= link_to aids_path do %>
        <div class="cat__card">
          <i class="fa-solid fa-kit-medical" id= "icon"></i>
          <h3>First-aid</h3>
        </div>
      <% end %>

      <%= link_to locations_index_path do %>
        <div class="cat__card">
          <i class="fa-solid fa-location-dot" id= "icon"></i>
          <h3>Location</h3>
        </div>
      <% end %>

      <%= link_to quizzs_path do %>
        <div class="cat__card">
          <i class="fa-solid fa-lightbulb" id= "icon"></i>
          <h3>Quizz</h3>
        </div>
      <% end %>

    </div>
  </section>


</div>

app/views/pages/index.html.erb
<div id="intro">
    <div id="content">
      <h2>Sauce</h2>
      <h3>Pu tir twa dan la, sauce !</h3>
    </div>
</div>

app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p>Find me in app/views/questions/show.html.erb</p>

app/views/quizzs/index.html.erb
<section class="container vh-100">

  <section id="quizz">
    <h2>QUIZZ TIME !</h2>
     <h3>Have fun . Learn . Save lifes </h3>
    <%= form_with url: quizzs_path, method: :get, class: "d-flex search_bar" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control search_icon",
        placeholder: "   Search"
      %>
      <button name="button" type="submit" class="btn btn-flat inner_icon">
        <i class="fas fa-search "></i>
      </button>
    <% end %>



    <div class="container cat__cards">
      <% @quizzs.each do |quizz| %>
        <%= link_to quizz_path(quizz) do %>
          <div class="cat__card">
            <%= quizz.name %>
          </div>
        <% end %>
      <% end %>
    </div>
  </section>

</section>

app/views/quizzs/show.html.erb
<section class="container vh-100" data-controller="quiz">
  <section id="question">
    <h2><%= @quizz.name %></h2>
    <% @quizz.questions.each_with_index do |question, index| %>
      <div class="my-question" data-quiz-target='correct' data-answer="<%= question.answer %>">
        <h3><%= question.name %></h3>
        <button class="btn" data-action="click->quiz#check<%= index %>" >
          <%= question.option1 %>
        </button>
        <button class="btn" data-action="click->quiz#check<%= index %>">
          <%= question.option2 %>
        </button>
        <button class="btn" data-action="click->quiz#check<%= index %>">
          <%= question.option3 %>
        </button>
      </div>
    <% end %>
  </section>
  <button type="button" class="d-none" data-bs-toggle="modal" data-bs-target="#exampleModal" data-quiz-target="trigger">
    Launch demo modal
  </button>
</section>
​
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">CONGRATS 🥳</h1>
        <%# <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <ul>
    <li class="footer-links active">
      <a href="/">
      <span class ="icon">
      <i class="fa-solid fa-house"></i>
      </span>
      <span class ="text">Home</span>
      </a>
    </li>

    <li class="footer-links active">
      <a href="/emergencies">
      <span class ="icon"><i class="fa-solid fa-phone"></i>
      </span>
      <span class ="text">Emergencies</span>
      </a>
    </li>

    <li class="footer-links active">
      <a href="/aids">
      <span class ="icon"><i class="fa-solid fa-briefcase-medical"></i>
      </span>
      <span class ="text">First-aids</span>
      </a>
    </li>

    <li class="footer-links active">
      <%= link_to locations_path, data: { turbo: false } do %>
        <i class="fa-solid fa-solid fa-location-dot"></i>
      <% end %>
      <div class=indicator></div>
    </li>

  </ul>

</div>

<%# <script>
const list = document.querySelectorAll('.list');
function activeLink(){
  list.forEach((item) =>
  item.classList.remove('active'));
  this.classList.add('active');
}
list,forEach((item) =>
item>addEventListener('click',activeLink))
</script> %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_nav_footer.html.erb
<div class="nav__footer">
  <ul>
    <li>
      <%= link_to emergencies_path, class: "n_icon", style:"#{'color:#16f943;'if request.original_fullpath == emergencies_path}" do %>
        <i class="fa-solid fa-phone"></i>
      <% end %>
    </li>

    <li>
      <%= link_to aids_path, class: "n_icon", style:"#{'color:#16f943;'if request.original_fullpath == aids_path}" do %>
        <i class="fa-solid fa-kit-medical"></i>
      <% end %>
    </li>

    <li>
      <%= link_to root_path, class: "n_icon" , style:"#{'color:#16f943;'if request.original_fullpath == root_path}" do %>
        <i class="fa-solid fa-house"></i>
      <% end %>
    </li>

    <li>
      <%= link_to locations_path, class: "n_icon" , style:"#{'color:#16f943;'if request.original_fullpath == locations_path}" do %>
        <i class="fa-solid fa-location-dot"></i>
      <% end %>
    </li>

    <li>
      <%= link_to quizzs_path, class: "n_icon", style:"#{'color:#16f943;'if request.original_fullpath == quizzs_path}" do %>
        <i class="fa-solid fa-lightbulb"></i>
      <% end %>
    </li>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h2>Sauce</h2>
    <% end %>

    <% if user_signed_in? %>
      <button class="navbar-toggler-self" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <%= image_tag "profile.jpg", class: "avatar dropdown-toggle" %>
      </button>
    <% else %>
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%# <li class="nav-item"> %>
            <%# <%= link_to "Action", "#", class: "nav-link" %>
          <%# </li> %>
          <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, class: "nav-link", data: {turbo_method: :delete} %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/steps/index.html.erb
<h1>Steps#index</h1>
<p>Find me in app/views/steps/index.html.erb</p>